# Generated by Django 4.1.4 on 2023-01-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_status_post_is_publish_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post/blog.png', upload_to='post'),
        ),
    ]
